# coding: utf-8

"""
    JupyterHub

    The REST API for JupyterHub

    The version of the OpenAPI document: 4.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.users_name_activity_post_request_servers_server_name import UsersNameActivityPostRequestServersServerName

class TestUsersNameActivityPostRequestServersServerName(unittest.TestCase):
    """UsersNameActivityPostRequestServersServerName unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersNameActivityPostRequestServersServerName:
        """Test UsersNameActivityPostRequestServersServerName
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersNameActivityPostRequestServersServerName`
        """
        model = UsersNameActivityPostRequestServersServerName()
        if include_optional:
            return UsersNameActivityPostRequestServersServerName(
                last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return UsersNameActivityPostRequestServersServerName(
                last_activity = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
        )
        """

    def testUsersNameActivityPostRequestServersServerName(self):
        """Test UsersNameActivityPostRequestServersServerName"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
