# coding: utf-8

"""
    JupyterHub

    The REST API for JupyterHub

    The version of the OpenAPI document: 4.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.users_name_patch_request import UsersNamePatchRequest

class TestUsersNamePatchRequest(unittest.TestCase):
    """UsersNamePatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> UsersNamePatchRequest:
        """Test UsersNamePatchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `UsersNamePatchRequest`
        """
        model = UsersNamePatchRequest()
        if include_optional:
            return UsersNamePatchRequest(
                name = '',
                admin = True
            )
        else:
            return UsersNamePatchRequest(
        )
        """

    def testUsersNamePatchRequest(self):
        """Test UsersNamePatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
