# coding: utf-8

"""
    JupyterHub

    The REST API for JupyterHub

    The version of the OpenAPI document: 4.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.proxy_patch_request import ProxyPatchRequest

class TestProxyPatchRequest(unittest.TestCase):
    """ProxyPatchRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ProxyPatchRequest:
        """Test ProxyPatchRequest
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ProxyPatchRequest`
        """
        model = ProxyPatchRequest()
        if include_optional:
            return ProxyPatchRequest(
                ip = '',
                port = '',
                protocol = '',
                auth_token = ''
            )
        else:
            return ProxyPatchRequest(
        )
        """

    def testProxyPatchRequest(self):
        """Test ProxyPatchRequest"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
