# coding: utf-8

"""
    JupyterHub

    The REST API for JupyterHub

    The version of the OpenAPI document: 4.0.2
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest
import datetime

from openapi_client.models.oauth2_token_post200_response import Oauth2TokenPost200Response

class TestOauth2TokenPost200Response(unittest.TestCase):
    """Oauth2TokenPost200Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Oauth2TokenPost200Response:
        """Test Oauth2TokenPost200Response
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Oauth2TokenPost200Response`
        """
        model = Oauth2TokenPost200Response()
        if include_optional:
            return Oauth2TokenPost200Response(
                access_token = '',
                token_type = ''
            )
        else:
            return Oauth2TokenPost200Response(
        )
        """

    def testOauth2TokenPost200Response(self):
        """Test Oauth2TokenPost200Response"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
